// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn-bW1WN-qQUowrjD_buxvlkvd2ib4s4k',
    appId: '1:283759670138:web:30ad7e2e010ee9baf59cc3',
    messagingSenderId: '283759670138',
    projectId: 'demomodul',
    authDomain: 'demomodul.firebaseapp.com',
    storageBucket: 'demomodul.firebasestorage.app',
    measurementId: 'G-T8R568SB6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQk6MWQ-6qDuw2HEeKtcey8TaLbaZhc_o',
    appId: '1:283759670138:android:9f908232f29237c8f59cc3',
    messagingSenderId: '283759670138',
    projectId: 'demomodul',
    storageBucket: 'demomodul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_43Urzl6IBmMYuVTGPAREmtuhpod9Tao',
    appId: '1:283759670138:ios:1f40646526ec4725f59cc3',
    messagingSenderId: '283759670138',
    projectId: 'demomodul',
    storageBucket: 'demomodul.firebasestorage.app',
    iosBundleId: 'com.example.demoModul4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_43Urzl6IBmMYuVTGPAREmtuhpod9Tao',
    appId: '1:283759670138:ios:1f40646526ec4725f59cc3',
    messagingSenderId: '283759670138',
    projectId: 'demomodul',
    storageBucket: 'demomodul.firebasestorage.app',
    iosBundleId: 'com.example.demoModul4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn-bW1WN-qQUowrjD_buxvlkvd2ib4s4k',
    appId: '1:283759670138:web:2aa1f34d5152d0f2f59cc3',
    messagingSenderId: '283759670138',
    projectId: 'demomodul',
    authDomain: 'demomodul.firebaseapp.com',
    storageBucket: 'demomodul.firebasestorage.app',
    measurementId: 'G-V3TW8CCX3N',
  );
}
